name: healthcare_360_mobile
description: A new Flutter project.

# Build using Flutter
# Version: 2.10.0
# Dart Version: 2.16.0
# Powered by FVM

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.3
  flutter_svg: ^1.0.0
  get: ^4.6.1
  provider: ^6.0.2
  shared_preferences: ^2.0.11
  introduction_screen: ^2.1.0
  image_picker: ^0.8.4+4
  tflite_flutter_helper: ^0.3.1
  lottie: ^1.3.0
  animated_text_kit: ^4.2.0
  webview_flutter: ^3.0.1
  connectivity_plus: ^2.3.4
  material_dialogs: ^1.1.1

  flutter_spinkit: ^5.1.0

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.3
  change_app_package_name: ^1.1.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/illustrations/
    - assets/svg/
    

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
